New subscriber api
koala-framework/kwc-newsletter pull request #23
Opened 2018-04-06 10:49 UTC by kaufmo

2018-04-09 10:11 UTC, nsams commented
warum ist der controller abstract?

und ich würde viel weniger code im controller machen sondern dafür einen (oder mehrere) services erstellen. Ist dann viel flexibler zum konfigurieren/überschreiben usw.

2018-04-09 10:14 UTC, nsams commented on Bundle/Controller/AbstractSubscribersController.php
> +        $this->subscribersHandler = $handler;
den nimmst du eigentlich nicht her, würd ich weglassen wenn du ihn eh nicht verwendest

2018-04-09 10:14 UTC, nsams commented on Bundle/Controller/AbstractSubscribersController.php
> +    private function setSubrootComponent($country = null)
ein controller (bzw. jeder service) sollte nichts "gesetzt" haben, sollte normalerweise zustandslos sein.

2018-04-09 10:15 UTC, nsams commented on Bundle/Controller/AbstractSubscribersController.php
> +    implements ClassResourceInterface
brauchst du nicht denke ich

2018-04-09 10:15 UTC, nsams commented
warum keine routing.yml? würde das nicht sinn machen?

2018-04-09 10:16 UTC, nsams commented on Bundle/Resources/config/services/controller.yml
> +        class: KwcNewsletter\Bundle\Controller\AbstractSubscribersController
sollte da (beim klassennamen und servicenamen) nicht vielleicht Api dazu?

2018-04-09 10:18 UTC, nsams commented
Und bitte eine Readme anlegen wo beschrieben ist was alles vorgesehen ist zu ändern bzw. wie man das macht.

2018-04-10 13:22 UTC, kaufmo commented
jetzt im nachhinein fallen mir auch einige verbesserungen ein werd das nochmal neu machen, ka was ich mir da gedacht hab XD

2018-05-11 06:50 UTC, kaufmo commented
@nsams, @fraxachun hab das ganze jetzt nochmal verbessert

2018-05-11 07:53 UTC, fraxachun requested changes

2018-05-11 07:53 UTC, fraxachun commented on Bundle/DependencyInjection/KwcNewsletterExtension.php
> +        $container->setParameter('kwc_newsletter.subscribers.api_country_param_is_required', $config['subscribers']['api_country_param_is_required']);
require_api_country_param oder
require_country_param_for_api

2018-05-11 07:53 UTC, fraxachun commented on Bundle/Controller/SubscribersApiController.php
> +    public function __construct(Subscribers $model, $isCountryRequired)
requireCountry

2018-05-11 08:02 UTC, fraxachun approved these changes

2018-05-11 13:15 UTC, nsams commented on Bundle/Controller/SubscribersApiController.php
> +        $this->setSubrootComponent($paramFetcher);
der controller sollte keinen zustand abhängig vom request haben

2018-05-11 13:15 UTC, nsams commented on Bundle/Controller/SubscribersApiController.php
> +            if (!$row->activated || $row->unsubscribed) {
im else sollte die category auch gesetzt werden falls sie noch nicht gesetzt ist

2018-05-14 05:07 UTC, kaufmo commented on Bundle/Controller/SubscribersApiController.php
> +        $this->setSubrootComponent($paramFetcher);
newsletter hat immer einen zustand nur welchen ist oben über eine config konfigurierbar, wie willst das sonst machen?

2018-05-14 05:08 UTC, kaufmo commented on Bundle/Controller/SubscribersApiController.php
> +            if (!$row->activated || $row->unsubscribed) {
fuck stimmt XD

2018-05-14 13:36 UTC, nsams approved these changes

2018-05-14 13:37 UTC, merged